baseURL: http://example.org/
languageCode: id-id
title: Batas Wilayah Indonesia
theme: "reveal-hugo"

markup:
  goldmark:
    renderer:
      unsafe: true

outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true